### ISSUE TITLE
Replace Highcharts

### ISSUE THREAD

**Issue by hazelshapiro** [nsidc/usaon-benefit-tool#308]
Sandy shared information about the Benefit Tool at a partnership meeting that included some developers. 

- The good news: The session was a smash success. Super high level of interest. 🎉 
- The question: A developer did follow up with some interest but in looking at our GitHub he said one of the pieces of code that we're using is not open source but requires a small site license. @MattF-NSIDC I'm wondering if you could clarify this (no rush) - Sandy and I don't understand the implications here. 

Sorry, 'bug fixes' may not be the best place for this, just want to be sure it's captured somewhere

**Comment by mfisher87** [comment]
An excellent observation. Last I checked, I believe it was when starting the prototype, Highcharts permitted non-commercial use without applying for a license, but that seems to have changed since then. I don't know if this applies to the version we're currently running or not, but my guess is the changed license applies retroactively or something. The only non-commercial free license option is now an "Educational license" which requires an application and lasts 1 year. We should move off of this software IMO. 

Highcharts is only used for rendering the Sankey diagrams, so replacing it won't touch very much code.

**Comment by hazelshapiro** [comment]
Thanks for this - very clear and now it does belong in the bugs category!

**Comment by mfisher87** [comment]
We got a new site license for Highcharts covering usaon.org and nsidc.org, so this is not as urgent anymore
