### ISSUE TITLE
List not showing up in decision records

### ISSUE THREAD

**Issue by hazelshapiro** [nsidc/usaon-benefit-tool#312]
https://usaon-benefit-tool.readthedocs.io/en/latest/reference/decision-records/002-level-of-detail.html

There should be a bulleted list within "Decision." Should be an easy fix, I don't know why the formatting isn't translating to the read the docs.

**Comment by mfisher87** [comment]
You're right, this one is easy :) The error is here: 

https://github.com/nsidc/usaon-benefit-tool/blob/c20521125d1e2d76fb910d58a402e50e14a508f5/doc/reference/decision-records/002-level-of-detail.md?plain=1#L23-L24

We need to leave a blank line before the start of the list so that the Markdown parser knows that it's not part of the previous paragraph. Would you be comfortable making the fix, @hazelshapiro ?
